# Generated by Django 4.0.4 on 2022-05-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('totalprice', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('catname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('passowrd', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('zip', models.IntegerField(default=0)),
                ('district', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('proid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('proprice', models.IntegerField()),
                ('proname', models.CharField(max_length=20)),
                ('promodel', models.CharField(max_length=10)),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Kapre.category')),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Kapre.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('reviewtext', models.CharField(max_length=50)),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Kapre.customer')),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Kapre.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('paytype', models.CharField(max_length=10)),
                ('cartid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Kapre.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='proid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Kapre.product'),
        ),
    ]
